openapi: 3.0.3
info:
  title: Avitolog API
  version: "1.0.0"
  description: |
    REST API for Avitolog: listings, ingest-by-URL, comments, and moderation.
    Auth uses Bearer JWT in Authorization header only.
servers:
  - url: /api
paths:
  /listings/:
    get:
      summary: Get most viewed listings
      description: |
        Returns most viewed listings ordered by views_count desc. Optional `limit` query param (default 20, max 50).
      parameters:
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
  /listings/{{id}}/:
    get:
      summary: Get listing by id
      description: Returns a listing by id and increments its views_count.
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '404':
          description: Listing not found
  /listings/ingest-url/:
    post:
      summary: Create or update listing by Avito URL
      description: |
        If a listing with the provided Avito URL exists, its basic fields are updated from Avito metadata; otherwise it is created.
        Allowed domain: avito.ru only.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [url]
              properties:
                url:
                  type: string
                  maxLength: 500
                  example: https://www.avito.ru/moskva/bytovaya_elektronika/iphone_14_pro_123456789
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '200':
          description: Updated/Existing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        '400':
          description: Invalid URL or domain
        '502':
          description: Failed to fetch Avito
  /listings/{{id}}/comments/:
    get:
      summary: List comments for listing
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '404':
          description: Listing not found
    post:
      security:
        - bearerAuth: []
      summary: Create comment for listing
      description: Auth required and user must not be blocked. Profanity is censored.
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
                  maxLength: 5000
                  example: Отличное объявление!
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: User is blocked
        '404':
          description: Listing not found
  /comments/{{comment_id}}/:
    delete:
      security:
        - bearerAuth: []
      summary: Delete comment
      description: Soft delete. Author can delete own comment, staff can delete any. ModerationLog is written.
      parameters:
        - in: path
          name: comment_id
          required: true
          schema: { type: integer }
      responses:
        '204': { description: Deleted }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
  /moderation/block-user/:
    post:
      security:
        - bearerAuth: []
      summary: Block user (staff only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id]
              properties:
                user_id: { type: integer }
                reason: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: User not found }
  /moderation/unblock-user/:
    post:
      security:
        - bearerAuth: []
      summary: Unblock user (staff only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id]
              properties:
                user_id: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: User not found }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Listing:
      type: object
      properties:
        id: { type: integer }
        url: { type: string }
        title: { type: string }
        image_url: { type: string, nullable: true }
        price: { type: number, format: double, nullable: true }
        description: { type: string }
        published_at: { type: string, format: date-time, nullable: true }
        views_count: { type: integer }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
    Comment:
      type: object
      properties:
        id: { type: integer }
        listing: { type: integer }
        user_id: { type: integer }
        user_username: { type: string }
        text: { type: string }
        created_at: { type: string, format: date-time }
    UserProfile:
      type: object
      properties:
        user_id: { type: integer }
        username: { type: string }
        is_blocked: { type: boolean }
        blocked_reason: { type: string, nullable: true }
        blocked_at: { type: string, format: date-time, nullable: true }
